return {
	{OP="Default",ID=1,Info="成功",},
	{OP="Default",ID=1001,Info="手机号不存在",},
	{OP="Default",ID=1002,Info="密码错误",},
	{OP="Default",ID=1003,Info="编号不存在",},
	{OP="Default",ID=1004,Info="编号与姓名不匹配",},
	{OP="Default",ID=1005,Info="手机空号",},
	{OP="Default",ID=1006,Info="号码黑名单",},
	{OP="Default",ID=1007,Info="本号码超出当天发送次数上限",},
	{OP="Default",ID=1008,Info="验证码不正确",},
	{OP="Default",ID=1009,Info="身份证号已存在",},
	{OP="Default",ID=1010,Info="银行卡号已存在",},
	{OP="Default",ID=1011,Info="手机号已存在",},
	{OP="Default",ID=1012,Info="请求过于频繁",},
	{OP="Default",ID=1013,Info="验证码错误",},
	{OP="Default",ID=1014,Info="身份证号已存在",},
	{OP="Default",ID=1015,Info="银行卡号已存在",},
	{OP="Default",ID=1016,Info="你现在的状态不能离岗",},
	{OP="Default",ID=1017,Info="你现在不能打下班卡",},
	{OP="Default",ID=1018,Info="你现在不能打上班卡",},
	{OP="Default",ID=1019,Info="你已登录，请稍候重试",},
	{OP="Default",ID=1020,Info="你还未登录",},
	{OP="Default",ID=1021,Info="你已巡店",},
	{OP="Default",ID=1022,Info="已注册",},
	{OP="Default",ID=1023,Info="密码错误",},
	{OP="Default",ID=1024,Info="更新失败",},
	{OP="Default",ID=1025,Info="不在打卡区域内",},
	{OP="Default",ID=1026,Info="已审核",},
	{OP="Default",ID=1027,Info="你已打卡",},
	
	{OP="Default",ID=2001,Info="上传出错",},
	{OP="Default",ID=2002,Info="没有上传照片",},
	{OP="Default",ID=2003,Info="上传照片类型不支持",},
	{OP="Default",ID=2004,Info="上传文件过大",},
	{OP="Default",ID=2005,Info="照片数量不足",},
	{OP="Default",ID=2006,Info="上传类型不存在",},
	{OP="Default",ID=2007,Info="参数类型错误",},
	
	{OP="Default",ID=3001,Info="已分配工作",},
	{OP="Default",ID=3003,Info=" 没有上传产品进度",},
	{OP="Default",ID=3004,Info=" 没有上传竞品分析",},
	{OP="Default",ID=3005,Info=" 没有该任务",},
	{OP="Default",ID=3006,Info=" 已过上班时间",},
	{OP="Default",ID=3007,Info=" 促销员时间重叠",},
	
	{OP="Default",ID=10000,Info="大量错误",},
}
